config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users do
    collection do
      get :add_friend, :group_create
    end
  end
  resources :rooms, only: [:new, :create, :show] do
    collection do
      post :group_create
    end
  end
  resources :ban, only: [:index]
  resources :messages, only: [:create]
  root 'users#index'


  get '/admin', to: 'admin/dashboards#index'
  namespace :admin do
    resources :users
    resources :rooms
    resources :messages
    resources :inappropriate_words
  end
end

app/models/inappropriate_word.rb
# == Schema Information
#
# Table name: inappropriate_words
#
#  id         :bigint(8)        not null, primary key
#  word       :string(255)      not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class InappropriateWord < ActiveRecord::Base
  validates :word, presence: true
end

app/controllers/admin/inappropriate_words_controller.rb
class Admin::InappropriateWordsController < Admin::BaseController
  def index
    @inappropriate_words = InappropriateWord.all
  end

  def new
    @inappropriate_word = InappropriateWord.new
  end

  def create
    @inappropriate_word = InappropriateWord.new(word_params)
    if @inappropriate_word.save
      redirect_to admin_inappropriate_words_path
    else
      render :new
    end
  end

  def delete
    @word = InappropriateWord.find(params[:id])
    @word.delete
  end

  private
  def word_params
    params.require(:inappropriate_word).permit(
      :word
    )
  end
end

app/views/admin/inappropriate_words/_form.html.haml
= form_for [:admin, @inappropriate_word] do |f|
  .form-group
    = f.label '不適切ワード', class: "col-sm-3 control-label"
    = f.text_field :word, class: "form-control", require: true
  = f.submit '送信する'

app/views/admin/inappropriate_words/index.html.haml
.container
  %table.table
    %thead.thead-light
      %tr
        %th 不適切ワード
        %th
    %tbody
      - @inappropriate_words.each do |word|
        %tr
          %td= word.word
          %td= link_to '削除する', admin_inappropriate_word_path(word),method: :delete, class:'btn btn-danger'
  = link_to '不適切ワードの追加', new_admin_inappropriate_word_path, class:'btn btn-hight'

app/views/admin/inappropriate_words/new.html.haml
= render 'form'