config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users do
    collection do
      get :add_friend, :group_create
    end
  end
  resources :rooms, only: [:new, :create, :show] do
    collection do
      post :group_create
    end
  end
  resources :ban, only: [:index]
  resources :messages, only: [:create]
  root 'users#index'


  get '/admin', to: 'admin/dashboards#index'
  namespace :admin do
    resources :users
    resources :rooms
    resources :messages
    resources :inappropriate_words
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint(8)        not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  name                   :string(255)      not null
#  image                  :string(255)
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  inappropriate_count    :integer          default(0), not null
#  status                 :integer          default("nomal"), not null
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

    validates :name, presence: true
    validates :image, presence: true

    has_many :user_rooms
    has_many :messages
    has_many :rooms, through: :user_rooms
    has_many :user_reads

    enum status: { nomal: 0, ban: 1}

    mount_uploader :image, ImageUploader
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  def index
    @q = User.ransack(params[:q])
    @users = @q.result(distinct: true)
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to admin_users_path
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_users_path
  end

  private
  def user_params
    params.require(:user).permit(:image, :name)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :user_account_ban?

  def index
    @user = current_user
    @rooms = @user.rooms.order(last_message_at: :desc)
  end

  def show
    @users = User.find(current_user.id)
  end

  def edit
    @user = current_user
  end

  def update
    current_user.update(user_params)
    redirect_to "/"
  end

  def add_friend
    @user = current_user
    # ユーザーの持っているルームを出す
    has_user_rooms = @user.rooms.not_group
    # そのルームに紐づくuser_idを配列で取る
    already_friends = UserRoom.where(room_id: has_user_rooms).pluck(:user_id).uniq
    # その配列以外のuser_idを持つユーザーを返す
    @users = User.where.not(id: already_friends).where.not(id: @user.id)
  end

  def group_create
    @room = Room.new
    @room.user_rooms.build
  end

  private
  def update_params
    params.require(:user).permit(:image, :name)
  end

  def user_account_ban?
    if user_signed_in?
      if current_user.ban?
        redirect_to ban_index_path
      end
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def read_counts(room, user)
    # roomの中の全てのメッセージの数を数える
    room_message_count = room.messages.where.not(user_id: user.id).count
    # その中でUserReadのレコードがあるものを数える
    user_read_count = 0
    room.messages.each do |message|
      if UserRead.find_by(room_id: room.id, user_id: user.id, message_id: message.id).present?
        user_read_count += 1
      end
    end
    count = room_message_count - user_read_count
    return count
  end
end

app/views/users/_group.html.haml
- @users.each do |user|
  .add-friend-box.mt-3
    = image_tag user.image_url(:square_md), class: 'user-img' if user.image.present?
    %h2.ml-3= user.name
    = link_to '友達になる！', rooms_path(user1_id: user.id, user2_id: current_user.id), method: :post, class:'btn btn-success add-btn'

app/views/users/_left_area.html.haml
= image_tag @user.image_url(:square_md), class:'user-img'
%h3= @user.name
-# #v-pills-tab.nav.flex-column.nav-pills{"aria-orientation" => "vertical", :role => "tablist"}
-#   %a#v-pills-messages-tab.nav-link.active{"aria-controls" => "v-pills-messages", "aria-selected" => "false", "data-toggle" => "pill", :href => "#v-pills-messages", :role => "tab"} メッセージ
-#   %a#v-pills-home-tab.nav-link{"aria-controls" => "v-pills-home", "aria-selected" => "true", "data-toggle" => "pill", :href => "#v-pills-home", :role => "tab"} 友だち追加
.d-none.d-lg-block
  .links
    %ul
      %li
        = link_to users_path(@user) do
          - if params[:controller] == 'users' && params[:action] == 'index'
            .active-tag メッセージ
          - else
            .no-active-tag メッセージ
      %li
        = link_to add_friend_users_path do
          - if params[:controller] == 'users' && params[:action] == 'add_friend'
            .active-tag 友だち追加
          - else
            .no-active-tag 友だち追加
      %li
        = link_to new_room_path do
          - if params[:controller] == 'rooms' && params[:action] == 'new'
            .active-tag グループ作成
          - else
            .no-active-tag グループ作成

app/views/users/_rooms.html.haml
- if @rooms.present?
  - @rooms.each do |room|
    =link_to room_path(room.id) do
      .rooms-box.mt-3
        - if room.is_group?
          = image_tag '/assets/group.jpg', class:'user-img mr-3'
          - room.users.each do |u|
            = u.name
        - else
          = image_tag room.users.where.not(id: current_user.id).first.image_url(:square_md), class:'user-img mr-3'
          = room.users.where.not(id: current_user.id).first.name
        %br
        - if room.messages.present?
          = room.messages.order(created_at: :desc).first.content.truncate(20)
        - unless read_counts(room, current_user).zero?
          .unread-count= read_counts(room, current_user)
- else
  まだ連絡をとっている人はいません

app/views/users/add_friend.html.haml
.container
  .row.mt-5
    .col-sm-3
      = render 'users/left_area'
    .col-sm-9
      -if @users.present?
        - @users.each do |user|
          .add-friend-box.mt-3
            = image_tag user.image_url(:square_md), class: 'user-img' if user.image.present?
            %h2.ml-3= user.name
            = link_to '友達になる！', rooms_path(user1_id: user.id, user2_id: current_user.id), method: :post, class:'btn btn-success add-btn'
      - else
        追加できる友達はいません。

app/views/users/index.html.haml
.container
  .row.mt-5
    .col-sm-3
      = render 'users/left_area'
    .col-sm-9
      = render 'rooms'