config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users do
    collection do
      get :add_friend, :group_create
    end
  end
  resources :rooms, only: [:new, :create, :show] do
    collection do
      post :group_create
    end
  end
  resources :ban, only: [:index]
  resources :messages, only: [:create]
  root 'users#index'


  get '/admin', to: 'admin/dashboards#index'
  namespace :admin do
    resources :users
    resources :rooms
    resources :messages
    resources :inappropriate_words
  end
end

app/controllers/admin/dashboards_controller.rb
class Admin::DashboardsController < Admin::BaseController
  def index
    @count_rooms = Room.all.count
    @count_users = User.all.count
    @count_inappropriate = InappropriateWord.all.count
  end
end

app/views/admin/dashboards/index.html.haml
.row
  .col-sm-4
    .card{:style => "width: 18rem;"}
      .card-body
        %h5.card-title 現在のユーザー数
        %p.card-text= "現在のユーザー数は#{@count_users}人です"
        = link_to 'ユーザー一覧へ', admin_users_path, class:'btn btn-primary'
  .col-sm-4
    .card{:style => "width: 18rem;"}
      .card-body
        %h5.card-title 現在のルーム数
        %p.card-text= "現在のルーム数は#{@count_rooms}個です"
        = link_to 'ルーム一覧へ', admin_rooms_path, class:'btn btn-primary'
  .col-sm-4
    .card{:style => "width: 18rem;"}
      .card-body
        %h5.card-title 不適切ワード一覧
        %p.card-text= "現在の不適切ワード数は#{@count_inappropriate}個です"
        = link_to '不適切ワード一覧へ', admin_inappropriate_words_path, class:'btn btn-primary'