config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users do
    collection do
      get :add_friend, :group_create
    end
  end
  resources :rooms, only: [:new, :create, :show] do
    collection do
      post :group_create
    end
  end
  resources :ban, only: [:index]
  resources :messages, only: [:create]
  root 'users#index'


  get '/admin', to: 'admin/dashboards#index'
  namespace :admin do
    resources :users
    resources :rooms
    resources :messages
    resources :inappropriate_words
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint(8)        not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  name                   :string(255)      not null
#  image                  :string(255)
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  inappropriate_count    :integer          default(0), not null
#  status                 :integer          default("nomal"), not null
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

    validates :name, presence: true
    validates :image, presence: true

    has_many :user_rooms
    has_many :messages
    has_many :rooms, through: :user_rooms
    has_many :user_reads

    enum status: { nomal: 0, ban: 1}

    mount_uploader :image, ImageUploader
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  def index
    @q = User.ransack(params[:q])
    @users = @q.result(distinct: true)
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to admin_users_path
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_users_path
  end

  private
  def user_params
    params.require(:user).permit(:image, :name)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :user_account_ban?

  def index
    @user = current_user
    @rooms = @user.rooms.order(last_message_at: :desc)
  end

  def show
    @users = User.find(current_user.id)
  end

  def edit
    @user = current_user
  end

  def update
    current_user.update(user_params)
    redirect_to "/"
  end

  def add_friend
    @user = current_user
    # ユーザーの持っているルームを出す
    has_user_rooms = @user.rooms.not_group
    # そのルームに紐づくuser_idを配列で取る
    already_friends = UserRoom.where(room_id: has_user_rooms).pluck(:user_id).uniq
    # その配列以外のuser_idを持つユーザーを返す
    @users = User.where.not(id: already_friends).where.not(id: @user.id)
  end

  def group_create
    @room = Room.new
    @room.user_rooms.build
  end

  private
  def update_params
    params.require(:user).permit(:image, :name)
  end

  def user_account_ban?
    if user_signed_in?
      if current_user.ban?
        redirect_to ban_index_path
      end
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def read_counts(room, user)
    # roomの中の全てのメッセージの数を数える
    room_message_count = room.messages.where.not(user_id: user.id).count
    # その中でUserReadのレコードがあるものを数える
    user_read_count = 0
    room.messages.each do |message|
      if UserRead.find_by(room_id: room.id, user_id: user.id, message_id: message.id).present?
        user_read_count += 1
      end
    end
    count = room_message_count - user_read_count
    return count
  end
end

app/views/admin/users/_form.html.haml
= form_for [:admin, @user] do |f|
  .form-group
    = f.label '名前', class: "col-sm-3 control-label"
    = f.text_field :name, class: "form-control", require: true
  .form-group
    = f.label '写真', class: "col-sm-3 control-label"
    = f.file_field :image, class: "form-control", require: true
  .form-group
    = f.label 'メールアドレス', class: "col-sm-3 control-label"
    = f.email_field :email, class: "form-control", require: true
  = f.submit '送信する'

app/views/admin/users/_search.html.haml
= search_form_for(@q, url: admin_users_path(params[:id]), method: :get, class:'form-group') do |f|
  .form-group.mt-3
    %h3= f.label "検索"
    .col-sm-6.pl-0= f.search_field :name_cont, placeholder: '名前', class:'form-control'
  .form-group
    .col-sm-6.pl-0= f.search_field :email_cont, placeholder: 'メールアドレス', class:'form-control'
  .form-group
    = f.submit "検索する", class: "btn btn-primary"

app/views/admin/users/edit.html.haml
.container
  %h3 ユーザー編集
  = render 'form'

app/views/admin/users/index.html.haml
.container
  = render 'search'
  %table.table
    %thead.thead-light
      %tr
        %th
        %th 名前
        %th メールアドレス
        %th 不適切ワード発言回数
        %th
        %th
    %tbody
      - @users.each do |user|
        %tr
          %th= image_tag user.image_url(:square_md), class: 'user-img'
          %td= user.name
          %td= user.email
          %td= user.inappropriate_count
          %td= link_to '編集する', edit_admin_user_path(user.id), class:'btn btn-info'